apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime
  namespace: default
spec:
  sources:
  - repoURL: https://helm.irsigler.cloud
    chart: uptime-kuma
    targetRevision: 2.14.2
    helm:
      valueFiles:
        - $values/02_UPTIME/values.yaml
  - repoURL: 'https://github.com/Cloud-Computing-2324/deployment-exercises-Yaro2003.git'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime
  project: default
  info:
    - name: 'Uptime Kuma'
      value: 'https://up.45.cc.ucll.cloud'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true