# values.yaml
ingress:
  enabled: true
  hosts:
    - host: up.45.cc.ucll.cloud
      paths:
        - path: "/"
          pathType: Prefix
resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
